### ISSUE TITLE
Hard Coded URLs ersetzen

### ISSUE THREAD

**Issue by Ciolv** [Ciolv/Doctor-Docs#66]

**Comment by romanwtk** [comment]
- [ ] localhost -> .env-Eintrag
- [ ] port -> .env-Eintrag
- [ ] MS-URLs jeweils .env-Einträge

**Comment by Ciolv** [comment]
Port wird nur im Backend saparat gespeichert.
Der API endpoint im Frontend kann theoretisch auch <domain>.<tld>:<port>/api sein. In diesem Fall kann der Port nicht separat gespeichert werden.
Im Backend ist das aber kein Problem.
