### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by Ciolv** [Ciolv/Doctor-Docs#68]
- [x] MongoDB
- [x] Express

**Comment by romanwtk** [comment]
By using mongodb+srv connection strings, connections are set up to TLS by default. I validated this with a Wireshark capture.

**Comment by romanwtk** [comment]
Next steps:
- [ ] Create signing request (``.cnf``-file)
- [ ] Sign this request with ``openssl`` (@Ciolv for running Linux)
- [ ] Change server with a https-Server (https://nodejs.org/api/https.html)
- [ ] Change Frontend (accept invalid/self-signed certificates)

**Comment by romanwtk** [comment]
closed with Backend-PR some minutes ago. Now every network request is encrypted.
